# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566c0b8a1019c058d0e0a233987f328fd635660453fe5784a505dc9619c4b906d078fcb1fdc641b21494e1d4b370908e7267715e4177fc1d2e24f4a265a073f2

test:
  secret_key_base: 3fbab8754c447e0fad3093b088bf210706370c410007fcd20ead38c6f83935a9fa94c86c4a367de67a2f937f1e5ac9f5ed0ab5e4921c8a7e846dc87492a2ab1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
